"""empty message

Revision ID: 86de9c009d3d
Revises: 
Create Date: 2019-06-07 01:58:33.476554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86de9c009d3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musics')
    # ### end Alembic commands ###
